"""Add dependencies and operation to rule table

Revision ID: 679394dc8fd9
Revises: ff9aab17097a
Create Date: 2025-06-24 04:22:34.286598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679394dc8fd9'
down_revision = 'ff9aab17097a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('rule_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dependencies', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('operation', sa.String(length=50), nullable=True))

    with op.batch_alter_table('segment_catalog', schema=None) as batch_op:
        batch_op.alter_column('operation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_catalog', schema=None) as batch_op:
        batch_op.alter_column('operation',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('rule_table', schema=None) as batch_op:
        batch_op.drop_column('operation')
        batch_op.drop_column('dependencies')

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('segment_output_5',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_16',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_9',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_14',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_3',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_11',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('upi_transactions_agg',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('total_transactions', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('last_transaction_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('favorite_category', sa.TEXT(), nullable=True),
    sa.Column('city_tier', sa.INTEGER(), nullable=True),
    sa.Column('period_start', sa.DATE(), nullable=False),
    sa.Column('period_end', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', 'period_end')
    )
    op.create_table('credit_card_payments_raw',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('transaction_id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transaction_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('merchant_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('city_tier', sa.INTEGER(), nullable=True),
    sa.Column('is_international', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('segment_output_7',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_13',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_8',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_10',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_4',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_2',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_6',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_12',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_15',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    op.create_table('segment_output_1',
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('total_transactions', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('total_spent', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('transaction_types', sa.NUMERIC(), nullable=True)
    )
    # ### end Alembic commands ###
